export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PRODUCT_INFO = 'SET_PRODUCT_INFO'

export const SET_TRIP_INFO = 'SET_TRIP_INFO'

export const SET_SELECTED_VISITOR = 'SET_SELECTED_VISITOR'

export const SET_EDIT_VISITOR = 'SET_EDIT_VISITOR'

export const SET_SERVER_STATUS = 'SET_SERVER_STATUS'

